name: Path Filter Workflow
on:
  push: 
    branches:
    - master
    paths:
    - 'src/**' # any file in src folder
    - 'pom.xml' # pom.xml change
    - 'Dockerfile' # docker file change

jobs:
   show-information:
         name: Push Trigger information
         runs-on : ubuntu-latest
         steps:
         - name: Show Trigger information
           run: |
              echo "Workflow triggered by Push Event"
              echo "Deatils of my workflow"
              echo "Event Name is : ${{ github.event_name }}"
              echo "Repository Name is : ${{ github.Repository }} "
              echo "Branch Name is : ${{ github.ref_name }} "
              echo "Actor Name is : ${{ github.actor }} "
              echo "Commit SHA is : ${{ github.sha }} "  