name: Pull Request Event
on:
  pull_request: 
jobs:
   show-information:
         name: Pull Request Event information
         runs-on : ubuntu-latest
         steps:
         - name: Pull Request Event information
           run: |
              echo "Workflow triggered by Pull Request Event"
              echo "Deatils of my Path Filter workflow"
              echo "Source Branch : ${{ github.head_ref }}"
               echo "Target Branch : ${{ github.base_ref }}"
              echo "Event Name is : ${{ github.event_name }}"
              echo "Repository Name is : ${{ github.repository }} "
             