name: Without Actions 
on: 
  workflow_dispatch
jobs:
   manual-setup:
      runs-on: ubuntu-latest  
      steps:
      - name: Manually Cloning the repo
        run: |
         echo "cloning the rep"
         git clone https://github.com/${{ github.repository }}.git .
         echo " List of Files after cloning"    
         echo "=====================" 
         ls - la
         echo "====================="
         pwd