name: FinalWF
on:
 workflow_run:
  workflows: 
  - InitialWF
  types:
  - completed
jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Print information
      run: |
         echo "Triggered from FinalWF Info"
         echo "Actor is ${{ github.actor }}"
         echo "comit sha is ${{ github.sha }}"
 
         