name: FinalWF
on:
 workflow_run:
  workflows: 
  - InitialWF
  types:
  - completed
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Print information
      run: |
         echo "Triggered FinalWF Info"
         echo "Actor is ${{ github.actor }}"
         echo "comit sha is ${{ github.sha }}"
         echo " Date time is ${{ github.Date }} , ${{ github.time }}"  
         